import { NextRequest, NextResponse } from 'next/server'
import { adminClient } from '@/lib/supabase/admin'
import { logEvent } from '@/lib/ledger'

export async function POST(req: NextRequest) {
  const { email, password, full_name, phone } = await req.json()

  if (!email || !password || !full_name) {
    return NextResponse.json({ error: 'Missing required fields' }, { status: 400 })
  }

  // Create auth user
  const { data: authData, error: authErr } = await adminClient.auth.admin.createUser({
    email,
    password,
    email_confirm: true,
  })

  if (authErr) return NextResponse.json({ error: authErr.message }, { status: 400 })

  // Create profile (rm_id auto-generated by trigger)
  const { data: profile, error: profileErr } = await adminClient
    .from('profiles')
    .insert({ id: authData.user.id, email, full_name, phone: phone ?? null })
    .select()
    .single()

  if (profileErr) {
    await adminClient.auth.admin.deleteUser(authData.user.id)
    return NextResponse.json({ error: profileErr.message }, { status: 400 })
  }

  await logEvent({
    eventType: 'auth.register',
    actorId: authData.user.id,
    entity: 'profiles',
    entityId: authData.user.id,
    payload: { rm_id: profile.rm_id, email, has_phone: !!phone },
    req,
  })

  return NextResponse.json({ rm_id: profile.rm_id, email: profile.email }, { status: 201 })
}
